### ISSUE TITLE
Make this mod client-side only

### ISSUE THREAD

**Issue by Neubulae** [LiquidwarpMC/go-down#1]
After some testing I realized I have to also install this on my server to make it work. Is therr any workaround to make it work client-side only?

**Comment by spascou** [comment]
Hey Sjakser !

Sadly I don't see a way to make this mod client-only. The pose change request has to be transmitted to the server with a custom handler.

I'll make it clear on the curseforge page however ! Thanks for the heads up.

**Comment by Neubulae** [comment]
> Hey Sjakser !
> 
> Sadly I don't see a way to make this mod client-only. The pose change request has to be transmitted to the server with a custom handler.
> 
> I'll make it clear on the curseforge page however ! Thanks for the heads up.

aww there's no way to *trick* the server into thinking you are actually stuck under a block? Well then, nice mod tho!
